services:
  sqlite:
    image: hibitdev/sqlite:latest
    container_name: sqlite
    volumes:
      - ./sqlite/data:/data
    command: /bin/sh -c "sqlite3 /data/app.db < /data/init.sql && tail -f /dev/null"

  api-server:
    build:
      context: .
    container_name: api-server
    volumes:
      - ./sqlite/data:/data
    ports:
      - "8080:8080"
    depends_on:
      - sqlite